In [1]:
import nltk
from nltk.stem import WordNetLemmatizer

In [2]:
example = "A cat was chasing the mice. there were cacti round the corner"
lemmatizer = WordNetLemmatizer()
example = [lemmatizer.lemmatize(token) for token in example.split(" ")]

In [3]:
example

['A',
 'cat',
 'wa',
 'chasing',
 'the',
 'mice.',
 'there',
 'were',
 'cactus',
 'round',
 'the',
 'corner']

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
vectorizer = TfidfVectorizer()

In [6]:
vectorizer.fit_transform(example)

<12x10 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [13]:
"""

Stemming
Lemmatizer
Vectorizer
Similarity Measure -
    - Manhattan Similarity
    - Euclidean Similarity
    - Cosine Similarity - X . Y / (||X|| * ||Y||)

"""

'\n\nStemming\nLemmatizer\nVectorizer\nSimilarity Measure -\n    - Manhattan Similarity\n    - Euclidean Similarity\n    - Cosine Similarity - X . Y / (||X|| * ||Y||)\n\n'

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
vect = TfidfVectorizer()
d1 = open("./1.txt", "r")
d2 = open("./2.txt", "r")
#d3 = open("./3.txt", "r")

corpus = [d1.read(), d2.read()]

d1.close()
d2.close()
#d3.close()
#corpus =["tesseract is good optical character recognition ", "Optical character recognition is significant", "Optical recognition is nice and good for" ,"the people who love image processing"]

In [29]:
vect.fit(corpus)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [30]:
vect.transform(["""If there is a phrase I would prefer to retire from online bios, personal or professional it is, "I love travel". Or some approximation of that sentiment. To clarify, I am not against ravellers or those who proudly flaunt their passion for travel. On the contrary, editing a travel magazine has now made me oddly protective of travellers and their ilk. My submission is that "love to travel", suggested so casually, just doesn't fell adequate to the depth of emotion it sparks in true devotess.  In february, the month of love as endowed by our great gifting industrial complex, we are wrestling with that "love for travel" means in tangible, life-affecting terms. The early thrones of discovering travel might not be too dissimilar to the beginnings of a feverish affair. A fleeting scene, sound or feeling that at first arouses, then enchants and eventually, lures us into hypnotic state, evoking woolly-eyed reveries about what could be.
This world however is not the most conductive for long-term passion. The kind that demans unflinching sustenance in the midst of distractions from a thousand notifications. Passion has many rivals to content with. and in flippantly announcing travel as our first love, we are not fully considering the influence our other paramours exert on us. Travellers for life are compulsive. They have to be, ther eis no other existence. Climate change, marriages, deaths, protests and politics might have to take a backseat. I am reminded of a wanderlist happy couple that discovered chinks in their relationshipdumped a road trip through RUssia. The woman was distraught, offered a solution, cut the short to come back home and rekindle their chemistry. The man, however,  would not give Siberia, despite a chance at a do-over. Passion dont """]).toarray()

array([[ 0.        ,  0.        ,  0.05239019,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.18638026,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.11182816,  0.        ,  0.        ,
         0.0745521 ,  0.        ,  0.0745521 ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.15717057,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.03727605,
         0.        ,  0.        ,  0.        ,  0. 

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
d2 = open("./2.txt", "r").read()
d1 = open("./1.txt", "r").read()


similarity = cosine_similarity(vect.transform(["""If there is a phrase I would prefer to retire from online bios, personal or professional it is, "I love travel". Or some approximation of that sentiment. To clarify, I am not against ravellers or those who proudly flaunt their passion for travel. On the contrary, editing a travel magazine has now made me oddly protective of travellers and their ilk. My submission is that "love to travel", suggested so casually, just doesn't fell adequate to the depth of emotion it sparks in true devotess.  In february, the month of love as endowed by our great gifting industrial complex, we are wrestling with that "love for travel" means in tangible, life-affecting terms. The early thrones of discovering travel might not be too dissimilar to the beginnings of a feverish affair. A fleeting scene, sound or feeling that at first arouses, then enchants and eventually, lures us into hypnotic state, evoking woolly-eyed reveries about what could be.
This world however is not the most conductive for long-term passion. The kind that demans unflinching sustenance in the midst of distractions from a thousand notifications. Passion has many rivals to content with. and in flippantly announcing travel as our first love, we are not fully considering the influence our other paramours exert on us. Travellers for life are compulsive. They have to be, ther eis no other existence. Climate change, marriages, deaths, protests and politics might have to take a backseat. I am reminded of a wanderlist happy couple that discovered chinks in their relationshipdumped a road trip through RUssia. The woman was distraught, offered a solution, cut the short to come back home and rekindle their chemistry. The man, however,  would not give Siberia, despite a chance at a do-over. Passion dont 
""", d2, d1]))
print (similarity)

[[ 1.          0.6431055   0.70891204]
 [ 0.6431055   1.          0.63495089]
 [ 0.70891204  0.63495089  1.        ]]
